'use client';

import { useEffect, useState } from 'react';
import { ArrowLeft, CheckCircle2, Mail, PackageCheck } from 'lucide-react';

export default function DeliveriesPage(){
  const [rows,setRows]=useState<any[]>([]);
  const [error,setError]=useState('');
  async function load(){const r=await fetch('/api/studio/deliveries',{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Failed');setRows(j.deliveries||[]);}
  useEffect(()=>{load().catch(e=>setError(e.message));},[]);
  return <main className="page"><header><button onClick={()=>window.location.href='/studio'}><ArrowLeft size={15}/> Studio</button><div><span>WORKSPACE / DELIVERIES</span><h1>Deliveries</h1></div><div/></header><div className="wrap"><div className="intro"><span>FINAL HANDOFFS</span><h2>What has been delivered.</h2><p>Every verified payment and final delivery is logged here.</p></div>{error&&<div className="error">{error}</div>}<div className="list">{rows.map(row=><div className="row" key={row.id}><div className="icon"><PackageCheck size={17}/></div><div className="main"><strong>{row.projectTitle||row.projectSlug}</strong><span>{row.clientEmail}</span></div><div className="files">{row.fileCount} file{row.fileCount==='1'?'':'s'}</div><div className="date">{row.sentAt}</div><span className="sent"><CheckCircle2 size={14}/> {row.status}</span></div>)}{!rows.length&&!error&&<div className="empty"><Mail size={28}/><strong>No deliveries yet</strong><span>Verified payments will appear here after final delivery.</span></div>}</div></div><style jsx>{`
.page{min-height:100vh;background:#07080a;color:#f5f5f6;font-family:Arial,sans-serif}.page header{height:72px;border-bottom:1px solid #202127;display:flex;align-items:center;justify-content:space-between;padding:0 30px}.page header button{height:35px;border:1px solid #2b2c32;background:#111216;color:#bbb;border-radius:8px;padding:0 11px;display:flex;align-items:center;gap:7px;font-size:9px}.page header>div span{font-size:7px;letter-spacing:1.7px;color:#5b5e67}.page header h1{font-size:15px;margin:5px 0 0}.wrap{max-width:1100px;margin:auto;padding:48px 22px}.intro>span{font-size:8px;letter-spacing:1.8px;color:#696c75;font-weight:800}.intro h2{font-size:30px;letter-spacing:-1.3px;margin:8px 0}.intro p{font-size:10px;color:#656871;margin-bottom:25px}.list{border:1px solid #222329;border-radius:15px;overflow:hidden;background:#101115}.row{display:flex;align-items:center;gap:13px;padding:14px 16px;border-bottom:1px solid #202127}.row:last-child{border:0}.icon{width:35px;height:35px;border-radius:9px;background:#172119;color:#70d69a;display:grid;place-items:center}.main{flex:1}.main strong,.main span{display:block}.main strong{font-size:10px}.main span{font-size:8px;color:#555861;margin-top:4px}.files,.date{font-size:8px;color:#777a83}.sent{font-size:8px;color:#71d599;display:flex;align-items:center;gap:5px}.empty{min-height:280px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:7px;color:#5d6068;font-size:9px}.empty strong{color:#bbb;font-size:12px}.error{padding:12px;border:1px solid #5a3030;background:#1d1214;color:#ffb4ae;border-radius:9px;font-size:10px;margin-bottom:12px}@media(max-width:700px){.page header{padding:0 14px}.page header>div{display:none}.wrap{padding:30px 14px}.date{display:none}.row{padding:12px}.files{display:none}}
`}</style></main>;
}
